2025-04-20 00:05:39,266 - root - INFO - {'is_train': True, 'is_rag': True, 'dataset_name': 'BGL', 'train_ratio': 0.8, 'window_size': 200, 'window_time': 1800, 'log_structed_path': './dataset/BGL/bgl-example.log_structured.csv', 'encoder_path': './pretrained', 'api_key': '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', 'api_base': 'https://api.openai-proxy.org/v1', 'llm_name': 'gpt-3.5-turbo', 'normal_class': 0, 'is_pretrain': False, 'optimizer_name': 'adam', 'lr': 0.0001, 'n_epochs': 150, 'lr_milestones': [50], 'batch_size': 40960, 'weight_decay': 0.0005, 'device': 'cuda:0', 'n_jobs_dataloader': 0, 'threshold': 0.8, 'topk': 5, 'prompt': 'prompt5', 'persist_directory': './output/ragdb-bgl'}
2025-04-20 00:06:35,755 - root - INFO - {'is_train': True, 'is_rag': True, 'dataset_name': 'BGL', 'train_ratio': 0.8, 'window_size': 200, 'window_time': 1800, 'log_structed_path': './dataset/BGL/bgl-example.log_structured.csv', 'encoder_path': './pretrained', 'api_key': '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', 'api_base': 'https://api.openai-proxy.org/v1', 'llm_name': 'gpt-3.5-turbo', 'normal_class': 0, 'is_pretrain': False, 'optimizer_name': 'adam', 'lr': 0.0001, 'n_epochs': 150, 'lr_milestones': [50], 'batch_size': 40960, 'weight_decay': 0.0005, 'device': 'cuda:0', 'n_jobs_dataloader': 0, 'threshold': 0.8, 'topk': 5, 'prompt': 'prompt5', 'persist_directory': './output/ragdb-bgl'}
2025-04-20 00:13:49,557 - root - ERROR - Configuration error: [Errno 2] No such file or directory: 'configs.yaml'
2025-04-20 00:15:38,078 - root - INFO - Starting LogRAG with config: {'is_train': True, 'is_rag': True, 'dataset_name': 'BGL', 'train_ratio': 0.8, 'window_size': 200, 'window_time': 1800, 'log_structed_path': './dataset/BGL/bgl-example.log_structured.csv', 'api_key': 'sk-your-valid-openai-key-here', 'llm_name': 'gpt-3.5-turbo', 'normal_class': 0, 'is_pretrain': False, 'optimizer_name': 'adam', 'lr': 0.0001, 'n_epochs': 150, 'lr_milestones': [50], 'batch_size': 40960, 'weight_decay': 0.0005, 'device': 'cuda:0', 'n_jobs_dataloader': 0, 'threshold': 0.8, 'topk': 5, 'prompt': 'prompt5', 'persist_directory': './output/ragdb-bgl'}
2025-04-20 00:15:38,464 - root - ERROR - Training failed: None is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo either by logging in with `huggingface-cli login` or by passing `token=<your_token>`
2025-04-20 00:15:38,468 - root - ERROR - Main execution failed: None is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo either by logging in with `huggingface-cli login` or by passing `token=<your_token>`
2025-04-20 00:26:39,158 - root - INFO - Starting LogRAG with config: {'is_train': True, 'is_rag': True, 'dataset_name': 'BGL', 'train_ratio': 0.8, 'window_size': 200, 'window_time': 1800, 'log_structed_path': './dataset/BGL/bgl-example.log_structured.csv', 'api_key': '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', 'llm_name': 'gpt-3.5-turbo', 'normal_class': 0, 'is_pretrain': False, 'optimizer_name': 'adam', 'lr': 0.0001, 'n_epochs': 150, 'lr_milestones': [50], 'batch_size': 40960, 'weight_decay': 0.0005, 'device': 'cuda:0', 'n_jobs_dataloader': 0, 'threshold': 0.8, 'topk': 5, 'prompt': 'prompt5', 'persist_directory': './output/ragdb-bgl'}
2025-04-20 00:26:39,545 - root - ERROR - Training failed: None is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo either by logging in with `huggingface-cli login` or by passing `token=<your_token>`
2025-04-20 00:26:39,545 - root - ERROR - Main execution failed: None is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo either by logging in with `huggingface-cli login` or by passing `token=<your_token>`
